// <auto-generated />
using System;
using Bonvivir.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bonvivir.Persistence.Migrations
{
    [DbContext(typeof(BonvivirDbContext))]
    [Migration("20190108150754_AddSource")]
    partial class AddSource
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bonvivir.Domain.Entities.Offer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<decimal>("Price");

                    b.Property<int>("Selection");

                    b.Property<string>("Source");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2019, 1, 8, 12, 7, 53, 978, DateTimeKind.Local).AddTicks(4607),
                            Price = 890m,
                            Selection = 0,
                            Title = "Oferta 1"
                        },
                        new
                        {
                            ID = 2,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2019, 1, 8, 12, 7, 53, 978, DateTimeKind.Local).AddTicks(5393),
                            Price = 1659m,
                            Selection = 1,
                            Title = "Oferta 2"
                        },
                        new
                        {
                            ID = 3,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2019, 1, 8, 12, 7, 53, 978, DateTimeKind.Local).AddTicks(5400),
                            Price = 1659m,
                            Selection = 2,
                            Title = "Oferta 3"
                        },
                        new
                        {
                            ID = 4,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2019, 1, 8, 12, 7, 53, 978, DateTimeKind.Local).AddTicks(5404),
                            Price = 1110m,
                            Selection = 3,
                            Title = "Oferta 4"
                        },
                        new
                        {
                            ID = 5,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2019, 1, 8, 12, 7, 53, 978, DateTimeKind.Local).AddTicks(5404),
                            Price = 2125m,
                            Selection = 4,
                            Title = "Oferta 5"
                        },
                        new
                        {
                            ID = 6,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2019, 1, 8, 12, 7, 53, 978, DateTimeKind.Local).AddTicks(5407),
                            Price = 790m,
                            Selection = 0,
                            Title = "Oferta 6 Exclusive Promo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
