// <auto-generated />
using System;
using Bonvivir.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bonvivir.Persistence.Migrations
{
    [DbContext(typeof(BonvivirDbContext))]
    [Migration("20190328155143_Adds Subscription, Address and Customer entities")]
    partial class AddsSubscriptionAddressandCustomerentities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bonvivir.Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apartment");

                    b.Property<string>("City");

                    b.Property<string>("District");

                    b.Property<string>("DoorNumber");

                    b.Property<string>("Floor");

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.Property<string>("ZipCode");

                    b.Property<string>("Zone");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Bonvivir.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BirthDate");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("IdNumber");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Bonvivir.Domain.Entities.Offer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BottlesQuantity");

                    b.Property<string>("Code");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<decimal>("Price");

                    b.Property<int>("Selection");

                    b.Property<string>("Source");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BottlesQuantity = 0,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2019, 3, 28, 12, 51, 43, 142, DateTimeKind.Local).AddTicks(1855),
                            Price = 890m,
                            Selection = 0,
                            Title = "Oferta 1"
                        },
                        new
                        {
                            ID = 2,
                            BottlesQuantity = 0,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2019, 3, 28, 12, 51, 43, 142, DateTimeKind.Local).AddTicks(2257),
                            Price = 1659m,
                            Selection = 1,
                            Title = "Oferta 2"
                        },
                        new
                        {
                            ID = 3,
                            BottlesQuantity = 0,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2019, 3, 28, 12, 51, 43, 142, DateTimeKind.Local).AddTicks(2260),
                            Price = 1659m,
                            Selection = 2,
                            Title = "Oferta 3"
                        },
                        new
                        {
                            ID = 4,
                            BottlesQuantity = 0,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2019, 3, 28, 12, 51, 43, 142, DateTimeKind.Local).AddTicks(2264),
                            Price = 1110m,
                            Selection = 3,
                            Title = "Oferta 4"
                        },
                        new
                        {
                            ID = 5,
                            BottlesQuantity = 0,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2019, 3, 28, 12, 51, 43, 142, DateTimeKind.Local).AddTicks(2267),
                            Price = 2125m,
                            Selection = 4,
                            Title = "Oferta 5"
                        },
                        new
                        {
                            ID = 6,
                            BottlesQuantity = 0,
                            CreatedBy = "Seed",
                            CreatedDate = new DateTime(2019, 3, 28, 12, 51, 43, 142, DateTimeKind.Local).AddTicks(2271),
                            Price = 790m,
                            Selection = 0,
                            Title = "Oferta 6 Exclusive Promo"
                        });
                });

            modelBuilder.Entity("Bonvivir.Domain.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressId");

                    b.Property<string>("ClubLaNacionCard");

                    b.Property<string>("CreditCard");

                    b.Property<int?>("CustomerId");

                    b.Property<string>("ExternalId");

                    b.Property<string>("Name");

                    b.Property<string>("PaymentMethodId");

                    b.Property<string>("PromotionId");

                    b.Property<string>("SchemaId");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Bonvivir.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("Bonvivir.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Bonvivir.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");
                });
#pragma warning restore 612, 618
        }
    }
}
