// <auto-generated />

namespace Bonvivir.WebApi.Controllers
{
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Bonvivir.Application.Address;
    using Bonvivir.Domain.Entities;
    using Bonvivir.Infrastructure.Exceptions;
    using Microsoft.AspNetCore.Mvc;

    [Route("api/[controller]")]
    public class AddressController : BaseController
    {
        // POST api/address/standardize
        [HttpPost("Standardize")]
        public async Task<ActionResult<IList<Selection>>> Standardize([FromBody] AddressRequest addressRequest)
        {
            try
            {
                return Ok(await Mediator.Send(addressRequest));
            }
            catch (KiwiApiException ex)
            {
                return StatusCode(ex.StatusCode, ex.ReasonPhrase);
            }
        }
    }
}
