// <auto-generated />

namespace Bonvivir.WebApi.Controllers
{
    using System.Threading.Tasks;
    using System.IdentityModel.Tokens.Jwt;
    using Bonvivir.Application.Authentication;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.IdentityModel.Tokens;
    using Microsoft.Extensions.Options;
    using Bonvivir.Domain.Helpers;
    using System.Text;
    using System.Linq;
    using System.Security.Claims;
    using System;
    using Microsoft.AspNetCore.Authorization;

    [Route("api/[controller]")]
    public class AuthenticationController : BaseController
    {
        public AuthenticationController(IOptions<AppSettings> appSettings)
        {
            _appSettings = appSettings.Value;
        }

        private readonly AppSettings _appSettings;

        // POST api/authentication/login
        [HttpPost("login")]
        public async Task<ActionResult<bool>> Login([FromBody] LoginRequest loginRequest)
        {
            return Ok(await Mediator.Send(loginRequest));
        }

        // GET api/authentication/IsAuthenticated
        [HttpGet("IsAuthenticated")]
        [Authorize]
        public ActionResult IsAuthenticated()
        {
            return Ok();
        }
    }
}
