// <auto-generated />

namespace Bonvivir.WebApi.Controllers
{
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Bonvivir.Application.Selections;
    using Bonvivir.Domain.Entities;
    using Microsoft.AspNetCore.Mvc;

    [Route("api/[controller]")]
    public class SelectionsController : BaseController
    {
        [HttpGet]
        public async Task<ActionResult<IList<Selection>>> GetSelection()
        {
            return Ok(await Mediator.Send(new SelectionsRequest()));
        }
    }
}
