// <auto-generated />

namespace Bonvivir.WebApi.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Bonvivir.Application.Leads;
    using Bonvivir.Domain.Entities;
    using Bonvivir.Infrastructure.Contracts;
    using MediatR;
    using Microsoft.AspNetCore.Mvc;

    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : BaseController
    {
        private readonly IKiwiClient _kiwiClient;

        public ValuesController(IKiwiClient kiwiClient)
        {
            _kiwiClient = kiwiClient;
        }

        // GET api/values
        [HttpGet]
        public ActionResult<IEnumerable<string>> Get()
        {
            return new string[] { "value1", "value2" };
        }
    }
}