import { createActions } from 'reduxsauce';

const { Types, Creators } = createActions(
  {
    getOffers: null,
    setLoginToken: ['data'],
    deleteLoginToken: null,
    setOffers: ['offers'],
    login: ['user'],
    setLoginError: null,
    isAuthenticated: null,
    setAuthenticationError: null,
    newOffer: ['formData'],
    editOffer: ['offer'],
    setAuthenticated: null,
    goToLogin: null,
    editItem: ['formData'],
    setLoadingFalse: null,
    deleteOffer: ['offer'],
    newItem: ['offerId', 'formData'],
    setNewItemError: ['message'],
    deleteItem: ['item'],
    getSubscriptionsWithError: ['errorCode', 'quantityPerPage', 'page'],
    setSubscriptionsWithError: ['subscriptionsWithError', 'totalQuantity'],
    setErrorOnGetSubscriptionsWithError: ['value'],
    exportToExcel: ['errorCode'],
    exportFile: ['data'],
    setErrorNumberSearch: ['value'],
    setPageSubscriptionWithError: ['value'],
    setQtyPerPage: ['value'],
    getTotalSubscriptionsWithError: ['errorCode', 'quantityPerPage', 'page'],
    setTotalSubscriptionsWithError: ['totalSubscriptionsWithError']
  },
  {
    prefix: 'BACKOFFICE/'
  }
);

const {
  getOffers,
  setOffers,
  login,
  editItem,
  setLoginToken,
  deleteLoginToken,
  deleteItem,
  setAuthenticated,
  setAuthenticationError,
  setLoginError,
  newOffer,
  setLoadingFalse,
  goToLogin,
  editOffer,
  isAuthenticated,
  newItem,
  deleteOffer,
  setNewItemError,
  getSubscriptionsWithError,
  setSubscriptionsWithError,
  setErrorOnGetSubscriptionsWithError,
  exportToExcel,
  exportFile,
  setErrorNumberSearch,
  setPageSubscriptionWithError,
  setQtyPerPage,
  getTotalSubscriptionsWithError,
  setTotalSubscriptionsWithError
} = Creators;

const {
  GET_OFFERS,
  SET_OFFERS,
  LOGIN,
  SET_LOGIN_ERROR,
  NEW_OFFER,
  EDIT_OFFER,
  SET_LOADING_FALSE,
  SET_LOGIN_TOKEN,
  DELETE_LOGIN_TOKEN,
  DELETE_OFFER,
  EDIT_ITEM,
  IS_AUTHENTICATED,
  GO_TO_LOGIN,
  NEW_ITEM,
  SET_AUTHENTICATED,
  SET_AUTHENTICATION_ERROR,
  DELETE_ITEM,
  SET_NEW_ITEM_ERROR,
  GET_SUBSCRIPTIONS_WITH_ERROR,
  SET_SUBSCRIPTIONS_WITH_ERROR,
  SET_ERROR_ON_GET_SUBSCRIPTIONS_WITH_ERROR,
  EXPORT_TO_EXCEL,
  EXPORT_FILE,
  SET_ERROR_NUMBER_SEARCH,
  SET_PAGE_SUBSCRIPTION_WITH_ERROR,
  SET_QTY_PER_PAGE,
  GET_TOTAL_SUBSCRIPTIONS_WITH_ERROR,
  SET_TOTAL_SUBSCRIPTIONS_WITH_ERROR
} = Types;

export {
  getOffers,
  setOffers,
  login,
  editItem,
  deleteItem,
  editOffer,
  goToLogin,
  setLoginError,
  setAuthenticationError,
  newOffer,
  IS_AUTHENTICATED,
  isAuthenticated,
  SET_AUTHENTICATED,
  setLoadingFalse,
  newItem,
  setLoginToken,
  deleteLoginToken,
  setAuthenticated,
  deleteOffer,
  setNewItemError,
  getSubscriptionsWithError,
  setSubscriptionsWithError,
  setErrorOnGetSubscriptionsWithError,
  exportToExcel,
  exportFile,
  setErrorNumberSearch,
  setPageSubscriptionWithError,
  setQtyPerPage,
  getTotalSubscriptionsWithError,
  setTotalSubscriptionsWithError,
  GET_OFFERS,
  SET_OFFERS,
  SET_LOADING_FALSE,
  GO_TO_LOGIN,
  DELETE_OFFER,
  SET_LOGIN_TOKEN,
  DELETE_LOGIN_TOKEN,
  SET_AUTHENTICATION_ERROR,
  DELETE_ITEM,
  EDIT_OFFER,
  LOGIN,
  SET_LOGIN_ERROR,
  EDIT_ITEM,
  NEW_OFFER,
  NEW_ITEM,
  SET_NEW_ITEM_ERROR,
  GET_SUBSCRIPTIONS_WITH_ERROR,
  SET_SUBSCRIPTIONS_WITH_ERROR,
  SET_ERROR_ON_GET_SUBSCRIPTIONS_WITH_ERROR,
  EXPORT_TO_EXCEL,
  EXPORT_FILE,
  SET_ERROR_NUMBER_SEARCH,
  SET_PAGE_SUBSCRIPTION_WITH_ERROR,
  SET_QTY_PER_PAGE,
  GET_TOTAL_SUBSCRIPTIONS_WITH_ERROR,
  SET_TOTAL_SUBSCRIPTIONS_WITH_ERROR
};

export default Creators;
