// <auto-generated />

namespace Bonvivir.WebApi.HealthChecks
{
    using System.Data.SqlClient;
    using System.Threading;
    using System.Threading.Tasks;
    using Bonvivir.Persistance;
    using Microsoft.Extensions.Diagnostics.HealthChecks;

    public class SqlServerHealthCheck : IHealthCheck
    {
        private readonly BonvivirDbContext _dbContext;

        public string Name => "sql";

        public SqlServerHealthCheck(BonvivirDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken = default(CancellationToken))
        {
            try
            {
                await _dbContext.Database.CanConnectAsync();
            }
            catch (SqlException)
            {
                return HealthCheckResult.Unhealthy();
            }

            return HealthCheckResult.Healthy();
        }
    }
}
