version: "3"

services:
  backend:
    build:
      context: ./api/
      dockerfile: Dockerfile
    env_file:
      - ".prod.env"
    ports:
      - 8080:8080
    expose:
      - "8080"

  encrypt:
    build: ./encrypt
    env_file: ".dev.env"
    expose:
      - "3000"

  frontend:
    build:
      context: ./ui/
      dockerfile: Dockerfile
    env_file:
      - ".prod.env"
    ports:
      - "80:5000"
    expose:
      - "5000"
    links:
      - backend
    depends_on:
      - backend
