const options = [
  { value: '67', description: 'CAPITAL FEDERAL' },
  { value: '66', description: 'BUENOS AIRES' },
  { value: '75', description: 'CATAMARCA' },
  { value: '72', description: 'CHACO' },
  { value: '85', description: 'CHUBUT' },
  { value: '88', description: 'CORDOBA' },
  { value: '87', description: 'CORRIENTES' },
  { value: '69', description: 'ENTRE RIOS' },
  { value: '80', description: 'FORMOSA' },
  { value: '89', description: 'JUJUY' },
  { value: '76', description: 'LA PAMPA' },
  { value: '70', description: 'LA RIOJA' },
  { value: '77', description: 'MENDOZA' },
  { value: '78', description: 'MISIONES' },
  { value: '81', description: 'NEUQUEN' },
  { value: '82', description: 'RIO NEGRO' },
  { value: '65', description: 'SALTA' },
  { value: '74', description: 'SAN JUAN' },
  { value: '68', description: 'SAN LUIS' },
  { value: '90', description: 'SANTA CRUZ' },
  { value: '83', description: 'SANTA FE' },
  { value: '71', description: 'SANTIAGO DEL ESTERO' },
  { value: '86', description: 'TIERRA DEL FUEGO' },
  { value: '84', description: 'TUCUMAN' }
];

const index = {
  capitalFederal: '67',
  buenosAires: '66',
  catamarca: '75',
  chaco: '72',
  chubut: '85',
  cordoba: '88',
  corrientes: '87',
  entreRios: '69',
  formosa: '80',
  jujuy: '89',
  laPampa: '76',
  laRioja: '70',
  mendoza: '77',
  misiones: '78',
  neuquen: '81',
  rioNegro: '82',
  salta: '65',
  sanJuan: '74',
  sanLuis: '68',
  santaCruz: '90',
  santaFe: '83',
  santiagoDelEstero: '71',
  tierraDelFuego: '86',
  tucuman: '84'
};

export { options, index };
